name: Node.js CI/CD Pipeline

# This specifies when the action should run. In this case, on push or pull requests to the master branch.
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# This defines the job called 'deploy', which runs on an Ubuntu runner.
jobs:
  deploy:
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job.
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # Sets up a specific version of Node.js
    - name: Set up Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '21.3.0' # Specify your Node.js version here

    # This step will SSH into your EC2 instance and execute deployment commands
    - name: SSH and Deploy
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.EC2_HOST }} # Your EC2 instance's IP or hostname
        username: ${{ secrets.EC2_USERNAME }} # EC2 instance username
        key: ${{ secrets.NODE_SERVER_SSH_KEY }} # SSH key for the EC2 instance
        script: |
          cd /home/ubuntu/ms-node-server # Change to your app's directory
          git pull origin master
          yarn # Install dependencies
          pm2 restart all # Restart the app using PM2
